---
name: ChangeLog

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      # we want our change information to be ready to go, but not yet batched
      # so the pipeline can manage it for us (and we don't have to worry about
      # versions/tags/etc)
      - name: Check for changelog entry
        uses: brettcannon/check-for-changed-files@v1.1.0
        with:
          file-pattern: |
            .changes/unreleased/*.yaml
          skip-label: skip changelog
          failure-message: Missing change entries waiting to be batched

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create new milestone
        id: createmilestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ steps.semvers.outputs.v_patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Batch changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: batch ${{ steps.semvers.outputs.v_patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Changes
        run: |
          git diff
          git status

      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/EndBug/add-and-commit#examples
      - uses: EndBug/add-and-commit@v9
        with:
          message: Bake changes for ${{ steps.semvers.outputs.v_patch }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
          tag: ${{ steps.semvers.outputs.v_patch }}
          default_author: github_actions
          add: |
            .changes/
            CHANGELOG.md
