---
name: Output Testing

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discover-test-cases:
    name: Discover test case directories
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.set-matrix.outputs.test-matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Set matrix
        id: set-matrix
        # yamllint disable rule:line-length
        run: |
          matches="$((cd terraform-test && /bin/ls -1d */) |sed 's!/!!' |jq -M -R -s -c 'split("\n")[:-1]')"
          echo "matches=${matches}"
          echo "::set-output name=test-matrix::${matches}"
        # yamllint enable rule:line-length
  debug-test-cases:
    runs-on: ubuntu-latest
    needs: discover-test-cases
    strategy:
      matrix:
        # yamllint disable-line rule:line-length
        test-directory: ${{ fromJson(needs.discover-test-cases.outputs.test-matrix) }}
    steps:
      - name: Debug
        # yamllint disable rule:line-length
        run: |
          echo "matrix=${{ toJson(needs.discover-test-cases.outputs.test-matrix) }}"
          echo "dir=${{ matrix.test-directory }}"
        # yamllint enable rule:line-length
