---
name: Output Testing

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spin_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        # yamllint disable rule:line-length
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        # yamllint enable rule:line-lengthprework
      - name: Set matrix
        id: discover-test-cases
        # yamllint disable rule:line-length
        run: |
          matches="$((cd terraform-test && /bin/ls -1d */) |sed 's!/!!' |jq -M -R -s -c 'split("\n")[:-1]')"
          echo "matches=${matches}"
          echo "DISCOVERED_TESTS='${matches}'" >> $GITHUB_OUTPUT
        # yamllint enable rule:line-length
      - name: Get Tests
        # yamllint disable rule:line-length
        run: echo "The discovered tests are ${{ steps.discover-test-cases.outputs.DISCOVERED_TESTS }}"
        # yamllint enable rule:line-lengthprework
      - name: Summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

    outputs:
      DISCOVERED: ${{ steps.discover-test-cases.outputs.DISCOVERED_TESTS }}
      SELECTED_COLORX: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}

  something_colorful:
    runs-on: ubuntu-latest
    needs: spin_up
    steps:
      - name: Get color
        # yamllint disable rule:line-length
        run: echo "The selected color is ${{ needs.spin_up.outputs.SELECTED_COLOR }}"
        # yamllint enable rule:line-length

  something_testy:
    runs-on: ubuntu-latest
    needs: spin_up
    strategy:
      matrix:
        # yamllint disable-line rule:line-length
        test-directory: ${{ needs.spin_up.outputs.DISCOVERED }}
    steps:
      - name: Debug
        # yamllint disable rule:line-length
        run: |
          echo "matrix=${{ toJson(needs.spin_up.outputs.DISCOVERED) }}"
        # yamllint enable rule:line-length
